[appearance.bar]
surface = "solid"
radius = "none"

[appearance]
opacity = 1
scale_factor = 1.2
workspace_colors = [ "#D385B5F2" ]
text_color = "#dddddd"

[appearance.background_color]
base = "#000000"
strong = "#222222"
weak = "#111111"

[appearance.primary_color]
base = "#D385B5F2"

[modules]
left = [ [ "Workspaces" ] ]
center = []
right = [ [ "Tray", "Settings", "Tempo" ] ]

[tempo]
clock_format = "%a %b %e %l:%M %P"

[settings]
indicators = [ "Bluetooth", "Network", "Audio", "Battery" ]
